### 220628

In [12]:
import platform
print(platform.python_version())

3.9.13


In [13]:
import os
print(os.getcwd())

c:\Users\rproject\Desktop\데이터청년캠퍼스\dachungcam


#### Data Type

In [14]:
a = 1
b = 1.2345
c = 3 + 4j

# 변수의 타입 확인
type(a)
type(b)
type(c)

complex

In [15]:
d = a + b + c
d

(5.2345+4j)

##### Str Type

In [16]:
sa = 'Hello Bigdata'
print(sa)

sb = "Hello Bigdata"
print(sb)

sc = """Hello Bigdata"""
print(sc)

sd = '''Hello Bigdata'''
print(sd)

se = 'and Cheer up!'
print(se)

Hello Bigdata
Hello Bigdata
Hello Bigdata
Hello Bigdata
and Cheer up!


In [17]:
print(sd + se)

Hello Bigdataand Cheer up!


In [18]:
a = "="
print(a)
print(a * 50)

=


In [19]:
# 문자열 길이
len(a)
len(se)
len(a * 50)

50

###### 문자열 인덱싱

In [20]:
a = 'this is a string'

print(a)
print(a[2])
print(a[0])
print(a[-1])
print(a[5])
print(a[4])

this is a string
i
t
g
i
 


###### 문자열 슬라이싱

- 끝번호 값은 제외하고 출력

In [21]:
b = '20200722Wed'

print(b)
print(b[0:4])
print(b[4:6])
print(b[:8])
print(b[8:])
print(b[:])
print(b[:-5])

20200722Wed
2020
07
20200722
Wed
20200722Wed
202007


###### 문자열 수정

In [22]:
a = 'this is a string'
a[10:] = 'rope'

TypeError: 'str' object does not support item assignment

In [23]:
b = 'robe'
a[:10] + b

'this is a robe'

In [24]:
# 문자 변경
c = a.replace('string', 'rope')
print(c)

this is a rope


###### 문자열 format

In [25]:
a = 11

# %d 숫자(정수)
"a equals %d." %3
"a equals %d." %a

'a equals 11.'

In [26]:
b = -22
"vars are %d and %d." %(a, b)

# %s 문자("" 꼭 넣어주기)
"I have %s children." %"three"
"vars are %s and %s." %(a, b)

"vars are %s and %s" %(3.14, 5)

# %숫자s 자리수만큼 공백 오른쪽 정렬 (-는 왼쪽 정렬)
"%10s" %"Good"
"%-10s" %"Good"

# 소수 자리수 출력
"%.5f" %3.141592
"%20.5f" %3.141592 # 전체 20자리 공간에서 오른쪽 정렬 소수점 5자리

'             3.14159'

###### 문자열 함수들

In [27]:
a = "Korean culture"

a.count('u')

a.find('u') # 문자 위치
a.find('K')
a.find('k') # -1 : 해당 문자 없음

a.index('u')
# a.index('k')

",".join('Korean culture') # 문자 사이 구분

a.upper()
a.lower()


'korean culture'

In [28]:
b = '     Korean cultrue   '

# 공백 제거
b.strip()
b.lstrip()
b.rstrip()


'     Korean cultrue'

In [29]:
a.replace("Korean", "American")
a.split()

['Korean', 'culture']

In [30]:
c = "Korean & American"
c.split("&")

['Korean ', ' American']

##### Boolean Type

In [31]:
d = True
type(d)

e = False

d and e
d or e
6 == 6
6 > 4
not d

# 문자열/리스트/튜플/딕셔너리가 비워져있으면 F
bool("ABC")
bool("")
bool([1, 2, 3])

# 0이면 F, 1이면 T
bool(0)
bool(1)

True

##### List Type

In [32]:
a = []
b = [1, 2, 3, 4, 5]
c = ['red', 'blue', 'yellow']
d = [1, 2, 'red', 'blue']
e = [1, 2, ['red', 'blue']]

print(a)
print(b)
print(c)
print(d)
print(e)

[]
[1, 2, 3, 4, 5]
['red', 'blue', 'yellow']
[1, 2, 'red', 'blue']
[1, 2, ['red', 'blue']]


###### 리스트 인덱싱

In [33]:
b[0]
b[0] + b[2]
b[-1]

5

In [34]:
a = [1, 2, 3, 4, 5, ['a', 'b', 'c', 'd'], 7, 8, 9]

print(a)

a[0]
a[-1]
a[5]
a[5][2]

[1, 2, 3, 4, 5, ['a', 'b', 'c', 'd'], 7, 8, 9]


'c'

###### 리스트 슬라이싱

In [35]:
b = [1, 2, 3, 4, 5]
b[0:4]

c = "12345"
c[0:4]

b[:3]
b[3:]

a[0:6]
a[0:6:1] # 한 자리마다 출력
a[0:6:2] # 두 자리마다 출력
a[0:6:3] # 세 자리마다 출력

a[5]
a[5][:2]

['a', 'b']

###### 리스트 연산

In [36]:
a = [1, 2, 3, 4]
b = [6, 7, 8, 9]

a + b
a * 2

len(a)

4

In [37]:
k = [12345678]
len(k)

m = '12345678'
len(m)

c = 'good'
# b + c

c = ['good']
b + c

[6, 7, 8, 9, 'good']

In [38]:
a[3] = 9
print(a)

n = '1234'
n[3]
n[3] = '9' # 문자열 수정 X

[1, 2, 3, 9]


TypeError: 'str' object does not support item assignment

###### 리스트 연산 함수

In [ ]:
a = [1, 2, 3, 4, [a, b, c]]
b = [6, 7, 8, 9]

len(a)
# sum(a)
sum(b)
max(b)
min(b)

6

In [ ]:
del(b[0]) #b[0] 삭제
print(b)

b = [6, 7, 8, 9]
del b[:3]
print(b)

str(b[0]) # 숫자형 -> 문자형 변경

[]
[9]


'9'

In [ ]:
b = ['6', '7', '8', '9']

b.append('10') # 기존 리스트에 추가
print(b)

b.append(['11', '12'])
print(b)

['6', '7', '8', '9', '10']
['6', '7', '8', '9', '10', ['11', '12']]


In [ ]:
c = ['6', '9', '8', '7']
print(c)

c.sort()
print(c)

['6', '9', '8', '7']
['6', '7', '8', '9']


In [ ]:
d = ['x', 'z', 'y']

d.sort()
print(d)

['x', 'y', 'z']


In [ ]:
c = ['6', '9', '8', '7']
c.reverse() # 역순으로 변환
print(c)

c.index('9')
# c.index('5')

c.insert(4, '10') # 4번 인덱스에 10 추가
print(c)

c.insert(0, '5')
print(c)

['7', '8', '9', '6']
['7', '8', '9', '6', '10']
['5', '7', '8', '9', '6', '10']


In [ ]:
e = ['3', '4', '3', '4', '5']

e.remove('4')
print(e)

e.remove('4')
print(e)

e.pop() # 마지막 요소 보여준 후, 삭제
print(e)

e.pop(1) # 1번 인덱스 요소 삭제
print(e)

e.pop(0)
print(e)

['3', '3', '4', '5']
['3', '3', '5']
['3', '3']
['3']
[]


In [ ]:
c = [6, 6, 6, 6, 6, 7, 8, 9]

c.count(6)
c.extend([4, 5]) # 요소 추가, 입력은 리스트만 가능
print(c)

c.append([4, 5])
print(c)

[6, 6, 6, 6, 6, 7, 8, 9, 4, 5]
[6, 6, 6, 6, 6, 7, 8, 9, 4, 5, [4, 5]]


##### Tuple Type

- 리스트는 대괄호, 튜플은 소괄호 사용
- 리스트는 수정 가능, 튜플은 수정 불가능
- 한 개의 요소만 갖는 경우, 마지막에 콤마(,) 필요 -> 그렇지 않으면 정수 타입 생성
- 값이 자주 변경되면 리스트, 항상 변하지 않으면 튜플

In [ ]:
a = tuple()
a = ()
type(a)

b = (1,)
type(b)

c = (1, 2, 3)
type(c)

d = 1, 2, 3 # 괄호 생략 가능
type(d)

e = 1, 2, ('ab', 'cd'), 3, 4
type(e)

tuple

In [ ]:
e[0]

# 튜플은 수정/변경 불가
# del e[0]
# e.remove[1]

e[:]

c + e
c * 2
len(c)

x, y, z = (1, 2, 3)
print(x, y, z)
print(x)

1 2 3
1


##### Dict Type

- key와 value를 한 쌍으로 가지고 있음

In [ ]:
a = {'gender':'Female', 'age':30, 'name':'Kristina'}
type(a)

# key 값을 입력하면, 그에 해당하는 value 반환
a['gender']
a['age']

# a[0]
a['Kristina']

KeyError: 'Kristina'

In [ ]:
b = {1:'good'}
print(b)

c = {'a':[1, 3, 5]}
print(c)

d = {'a':(1, 3, 5)}
print(d)

{1: 'good'}
{'a': [1, 3, 5]}
{'a': (1, 3, 5)}


In [ ]:
# key 자리에 리스트 사용 X
# c = {[1, 3, 5 : 'a']}

# 튜플 사용 O
d = {(1, 3, 5) : 'a'}

In [ ]:
a = {'gender' : 'Femal'}
a['age'] = 30 # key value 추가
print(a)

a['name'] = 'Kristina'
print(a)

a['a'] = [1, 3, 5]
print(a)

{'gender': 'Femal', 'age': 30}
{'gender': 'Femal', 'age': 30, 'name': 'Kristina'}
{'gender': 'Femal', 'age': 30, 'name': 'Kristina', 'a': [1, 3, 5]}


In [ ]:
# key와 value 한 쌍이 같이 삭제
del a['a']
print(a)

del a['name']
print(a)

{'gender': 'Femal', 'age': 30, 'name': 'Kristina'}
{'gender': 'Femal', 'age': 30}


In [ ]:
a = {'gender':'Female', 'age':30, 'name':'Kristina'}

a.keys()
list(a.keys())

a.values()
a.items()

a.clear() # 딕셔너리 내 모든 요소 삭제
print(a)

{}


In [ ]:
a = {'gender':'Female', 'age':30, 'name':'Kristina'}

a.get('gender')
a.get('height', '?') # key가 딕셔너리 내에 값이 없을 때, ?로 표현

# 값이 있으면 T, 없으면 F
'gender' in a
'height' in a

False

### 220629

#### 연산

##### 수치 연산

In [39]:
2 + 3
3 - 2
2 * 3
3.14 ** 2 # 제곱승
2 ** .5
5 / 2
5 // 2 # 몫
5 % 2 # 나머지

1

In [40]:
a = 6
b = 4

a + b
a - b
a ** b
a / b
a // b
a % b

2

##### 대입 연산

In [41]:
a = 20

a += 5
print(a)

a -= 10
print(a)

a += 2
print(a)

a /= 3
print(a)

25
15
17
5.666666666666667


In [42]:
a = 3
b = 2

a += 2 + b
print(a)

a += b - 5
print(a)

7
4


##### 비교 연산

In [43]:
a = 95

a == 90
a != 90
a > 90
a < 90
a >= 90
a <= 90
a >= 90 and a <= 100
90 <= a <= 100
100 <= a <= 110
70 <= a <= 80

False

##### 논리연산

In [44]:
a = True
b = False

a and b
a and a
b and b

a or b
a or a
b or b

# 반대되는 논리 연산
not a
not (a and b)

True

##### 구성원 연산

In [45]:
a = [1, 2, 'Hello Data']

1 in a
a not in a
3 in a
3 not in a


b = {'a':1, 'b':2, 'c':3}

'a' in b
'k' in b
1 in b # key 값에 없음

False

##### 활용

In [46]:
a = [
{'num':'1', 'name':'김철수', 'kor':90, 'eng' : 80, 'math':85, 'total':0, 'avg':0.0},
{'num':'2', 'name':'박민주', 'kor':90, 'eng' : 85, 'math':90, 'total':0, 'avg':0.0},
{'num':'3', 'name':'박영호', 'kor':80, 'eng' : 80, 'math':80, 'total':0, 'avg':0.0}]

a[0]
a[0]['total']
a[0]['total'] = 1 # total의 value 1로 지정
a[0]

{'num': '1',
 'name': '김철수',
 'kor': 90,
 'eng': 80,
 'math': 85,
 'total': 1,
 'avg': 0.0}

In [47]:
# 학생별 합계 구하기
a[0]['total'] = a[0]['kor'] + a[0]['eng'] + a[0]['math']
a[1]['total'] = a[1]['kor'] + a[1]['eng'] + a[1]['math']
a[2]['total'] = a[2]['kor'] + a[2]['eng'] + a[2]['math']

a[0]['total']
a[1]['total']
a[2]['total']

240

In [48]:
# 학생별 평균 구하기
a[0]['avg'] = a[0]['total']/3
a[1]['avg'] = a[1]['total']/3
a[2]['avg'] = a[2]['total']/3

print(a)

[{'num': '1', 'name': '김철수', 'kor': 90, 'eng': 80, 'math': 85, 'total': 255, 'avg': 85.0}, {'num': '2', 'name': '박민주', 'kor': 90, 'eng': 85, 'math': 90, 'total': 265, 'avg': 88.33333333333333}, {'num': '3', 'name': '박영호', 'kor': 80, 'eng': 80, 'math': 80, 'total': 240, 'avg': 80.0}]


In [49]:
# 학급평균 구하기
b = (a[0]['total'] + a[1]['total'] + a[2]['total']) / 3
print(b)

253.33333333333334


#### 조건문

##### if문

In [50]:
x = 5
if x < 10 :
    a = 1

a

1

##### if-else문

In [51]:
if True :
    print('참입니다')
else :
    print('거짓입니다')

if False :
    print('참입니다')
else :
    print('거짓입니다')

참입니다
거짓입니다


In [52]:
a = 1000

if a > 5000 :
    print('택시를 탑니다')
else :
    print('버스를 타야합니다')

if a <= 5000 :
    print('택시를 탑니다')
else :
    print('버스를 타야합니다')

버스를 타야합니다
택시를 탑니다


In [53]:
# input 사용자에게 입력받은 값을 변수에 저장
# float 실수형으로 변환 / int 정수형으로 변환 / str 문자형으로 변환

grade = float(input('총 평점을 입력해 주세요 : '))

if grade >= 4.3 :
    print('당신은 장학급 수여 대상자입니다')
    print('축하합니다')

ValueError: could not convert string to float: ''

In [ ]:
data = int(input('숫자를 입력하시오 : '))

if data % 2 == 0 :
    print('입력된 값은 짝수입니다.')
else :
    print('입력된 값은 홀수입니다.')

입력된 값은 홀수입니다.


##### if-elif-els문

- 조건이 여러개일 때

In [ ]:
x = 5

if x < 10 :
    a = 1
elif 10 <= x and x < 20 :
    a = 2
else :
    a = 3

a

1

##### 중첩 if문

In [ ]:
age = int(input('나이를 입력하세요 : '))
height = int(input('키를 입력하세요 : '))

if age >= 40 :
    if height >= 170 :
        print('키가 보통 이상입니다')
    else :
        print('키가 보통입니다')
else :
    if height >= 175 :
        print('키가 보통 이상입니다')
    else :
        print('키가 보통입니다')

키가 보통입니다


##### 간략한 if-else문

- if문과 else문 뒤에 수행할 문장이 한 줄인 경우
- (참일 경우 실행문) if (조건문) else (거짓일 경우 실행문)

In [ ]:
score = 80

if score >= 70 :
    a = "good"
else :
    a = "bad"

a = "good" if score >= 70 else "bad"

a

'good'

#### 반복문

##### for문

In [ ]:
for a in [1, 2, 3] :
    print(a)

for a in [[1, 3], [5, 7], [9]] :
    print(a)

for a in [(1, 3), {5, 7}, 9] :
    print(a)

1
2
3
[1, 3]
[5, 7]
[9]
(1, 3)
{5, 7}
9


In [ ]:
(a, b) = (1, 2)
print(a)
print(b)
print(a, b)

1
2
1 2


In [ ]:
for (a, b) in [(1, 2), (3, 4), (5, 6)] :
    print(a + b)

3
7
11


In [ ]:
a = "Hello!"
b = ["Hello!", "Data"]
c = (1, 2, 3)

for x in a :
    print(x)

for x in a :
    print(x, end = "")

H
e
l
l
o
!
Hello!

In [ ]:
for x in b :
    print(x)

for x in c :
    print(x)

Hello!
Data
1
2
3


In [ ]:
d = {'circle':2, 'rectangle':3, 'line':1}
e = {'red', 'green', 'blue', 'red'}

# dict는 key 값만 출력
for x in d :
    print(x)

# 순서가 없고, 중복 허용 X
for x in e :
    print(x)

circle
rectangle
line
red
blue
green


###### range

In [54]:
list(range(3, 31, 3))

result = 0

for i in list(range(1, 11, 2)) :
    result = result + 3
    print(result)

3
6
9
12
15


In [55]:
lst = [1, 2, 3, 4, 5]
result = [ ]

for num in lst :
    result.append(num * 3)

print(result) 

[3, 6, 9, 12, 15]


In [56]:
lst = [1, 2, 3, 4, 5]
result = [num * 3 for num in lst]
print(result)

[3, 6, 9, 12, 15]


In [57]:
result = [num * 3 for num in lst if num % 2 == 0]
print(result)

[6, 12]


###### 이중 for문

In [58]:
# print 구문의 위치에 따라서 결과값이 달라짐
for a in range(2, 10) :
    for b in range(1, 10) :
        print(a * b, end = " ")
    print(' ')

for a in range(2, 10) :
    for b in range(1, 10) :
        print(a * b)
    print(' ')

2 4 6 8 10 12 14 16 18  
3 6 9 12 15 18 21 24 27  
4 8 12 16 20 24 28 32 36  
5 10 15 20 25 30 35 40 45  
6 12 18 24 30 36 42 48 54  
7 14 21 28 35 42 49 56 63  
8 16 24 32 40 48 56 64 72  
9 18 27 36 45 54 63 72 81  
2
4
6
8
10
12
14
16
18
 
3
6
9
12
15
18
21
24
27
 
4
8
12
16
20
24
28
32
36
 
5
10
15
20
25
30
35
40
45
 
6
12
18
24
30
36
42
48
54
 
7
14
21
28
35
42
49
56
63
 
8
16
24
32
40
48
56
64
72
 
9
18
27
36
45
54
63
72
81
 


###### for문 안에 조건문(if-else)

In [59]:
Score = [100, 7, 75, 32]
num = 0

for a in Score :
    num += 1
    if a >= 70 :
        print('%d번 합격' %num)
    else :
        print('%d번 불합격' %num)

1번 합격
2번 불합격
3번 합격
4번 불합격


##### While문

In [60]:
i = 1

while i < 10 :
    result = 2 * i
    print(result)
    i += 1

2
4
6
8
10
12
14
16
18


In [61]:
a = 1
b = 0

while a <= 100 :
    b = b + a
    a = a + 1
    
print('1부터 100까지의 합은 : ', b)

1부터 100까지의 합은 :  5050


###### break

- 특정 조건을 만족하면 반복문 강제 종료

In [62]:
a = 1
b = 0

while a <= 100 :
    b = b + a
    a = a + 1
    
    if b > 3000 :
        break


print('1부터 100까지의 합은 : ', b)

1부터 100까지의 합은 :  3003


In [63]:
result = [ ]

for i in range(1, 6) :
    for j in range(1, 11) :
        k = i * j
        result_temp = [i, j, k]
        
        if k > 10 :
            break
        result.append(result_temp)

print(result)

[[1, 1, 1], [1, 2, 2], [1, 3, 3], [1, 4, 4], [1, 5, 5], [1, 6, 6], [1, 7, 7], [1, 8, 8], [1, 9, 9], [1, 10, 10], [2, 1, 2], [2, 2, 4], [2, 3, 6], [2, 4, 8], [2, 5, 10], [3, 1, 3], [3, 2, 6], [3, 3, 9], [4, 1, 4], [4, 2, 8], [5, 1, 5], [5, 2, 10]]


###### continue

- 해당 step을 실행하지 않고 건너뜀

In [64]:
Score = [100, 7, 75, 32]
num = 0

for a in Score :
    num += 1
    
    if a < 70 :
        continue
    else :
        print('%d번 합격' %num)

1번 합격
3번 합격


#### 사용자 정의 함수

In [65]:
def square(x) :
    return x * x

square(5)

25

In [66]:
def even_or_odd(n) :
    if n % 2 == 0 :
        print("even")
        return
    print("odd")

even_or_odd(3)
even_or_odd(4)

odd
even


In [67]:
def Function_1(a, b) :
    x = a + 5
    y = b * 3
    z = x + y
    return z

Function_1(1, 5)
Function_1(a = 1, b = 5)

21

- 입력변수가 몇 개인지 모를 때, 매개변수 앞에 `*` 추가

In [68]:
def add_many(*args) :
    result = 0

    for i in args :
        result += i
    return result

add_many(1, 2, 3)
add_many(1, 2, 3, 4)

10

In [69]:
def add_many(choice, *args) :
    result = 0

    if choice == "good" :
        for i in args :
            result += i
    elif choice == "bad" :
        for i in args :
            result -= i
    return result

add_many("good", 1, 2, 3, 4, 5, 6)
add_many("bad", 1, 2, 3, 4, 5, 6)

-21

- 조건을 만족하면, return 함수로 함수 빠져나옴

In [70]:
def say_nick(nick) :
    if nick == "바보" :
        return
    print("나의 별명은 %s 입니다." %nick)

say_nick("바보")
say_nick("천재")

나의 별명은 천재 입니다.


- 매개변수에 초기 값 입력

In [71]:
def say_myself(name, old, man = True) :
    print("나의 이름은 %s 입니다." %name)
    print("나이는 %d살입니다." %old)

    if man :
        print("남자입니다.")
    else :
        print("여자입니다.")

say_myself("민주", 41)

나의 이름은 민주 입니다.
나이는 41살입니다.
남자입니다.


In [72]:
a = 1

def vartest(a) :
    a += 1

vartest(a)

print(a)

1


In [73]:
a = 1

def vartest(a) :
    a += 1
    return a

a = vartest(a)
print(a)

2


In [74]:
a = 1

def vartest() :
    global a
    a += 1

vartest()
print(a)

2


### 220630

In [75]:
pip install numpy


[notice] A new release of pip available: 22.1.2 -> 22.2
[notice] To update, run: C:\Users\rproject\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [76]:
import numpy as np

##### 배열과 리스트 비교

- 배열은 모든 원소가 같은 자료형이어야 하고, 리스트는 각각의 원소가 다른 자료형이 될 수 있음
- 배열은 원소의 갯수를 변경할 수 없음

In [77]:
a = np.array(([1, 2], [3, 4])) # 배열
b = [[1, 2], [3, 4]] # 리스트

a
b

a[1, 1]
b[1][1]

4

###### 1차원 배열

In [78]:
data1 = [1, 2, 3, 4, 5]
data1

data2 = [1, 2, 3, 3.5, 4]
data2

# numpy를 이용하여 array 정의
arr1 = np.array(data1)
arr1

# array의 형태(크기) 확인
arr1.shape


arr2 = np.array([1, 2, 3, 4, 5])
arr2

arr2.shape

# array의 자료형
arr2.dtype


arr3 = np.array(data2)
arr3

arr3.shape
arr3.dtype

dtype('float64')

###### 2차원 배열

In [79]:
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr4

arr4.shape

(4, 3)

###### 3차원 배열

In [80]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
type(arr5)
arr5.shape

(2, 4, 3)

###### 기타 배열

- np.zeros : 모든 요소가 0인 array
- np.ones : 모든 요소가 1인 array
- np.arange : 1씩 증가하는 1차원 array
- np.full : 특정 값으로채움
- np.eye : 단위 행렬
- np.empty : 초기화되지 않은 값으로 배열 생성

In [81]:
np.zeros(10)
np.zeros((3, 5))

np.ones(9)
np.ones((2, 10))

np.arange(10) # 0부터 9까지
np.arange(3, 10) # 3부터 9까지

np.full((2, 2), 7) # 2*2 array에 7로 full

np.eye(4)

np.empty((4, 2)) # 메모리 초기화되지 않아, 예상치 못한 garbage value가 포함

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.17785250e-320],
       [0.00000000e+000, 1.11326265e-308]])

In [82]:
# 동일한 구조와 데이터 형태를 유지한 상태로, 각 "0, 1, 빈 배열" 반환
a = np.arange(1, 10).reshape(3, 3)
a

np.zeros_like(a)
np.ones_like(a)
np.empty_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##### Array 연산

- 크기가 동일한 array끼리 연산
- 같은 위치에 있는 요소들끼리 연산

In [83]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1.shape

arr2 = np.array([[10, 11, 12], [13, 14, 15]])
arr2.shape

arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [84]:
# 브로드 캐스트 - 크기가 다른 array 연산 가능
arr1.shape

arr3 = np.array([10, 11, 12])
arr3.shape

arr1 + arr3
arr1 * 10
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

###### Array의 인덱싱

In [85]:
arr1 = np.arange(10)

arr1[0]
arr1[3]
arr1[3:9]
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# 다차원 배열에서 각 차원에 대해 가능

arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr2[0, 0]
arr2[2, :]
arr2[2, 3]
arr2[:, 3]
arr2[[2, 0, 1], :] # 행 순서 변경

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [87]:
# boolean 인덱싱 (마스크) - 원하는 행 또는 열의 값만 추출 (TRUE 값)

data = np.random.randn(8, 4) # 가우시안 정규분포
data

data = np.random.randint(0, 100, size= (8, 4))
data

type(data)
data.shape

(8, 4)

In [88]:
data[:, 0] < 50 # boolean 값
data[data[:, 0] < 50, :]
data[data[:, 0] < 50, 2:4]
data[data[:, 0] < 50, 2:4] = 0
data

array([[43, 92,  0,  0],
       [76, 61, 65, 95],
       [64, 28, 20, 42],
       [61, 38, 17, 38],
       [57, 99, 10,  9],
       [29, 69,  0,  0],
       [ 6, 12,  0,  0],
       [53,  5, 25,  1]])

In [89]:
arr2[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [91]:
names = np.array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park', 'Beomwoo'])

names
names.shape

(8,)

In [93]:
names[0, ]
names[4, ]

'Lee'

In [94]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [95]:
data[names_Beomwoo_mask, :]

array([[43, 92,  0,  0],
       [76, 61, 65, 95],
       [29, 69,  0,  0],
       [53,  5, 25,  1]])

In [97]:
# 요소가 Kim인 행의 데이터만 꺼내기
names == 'Kim'

data[names == 'Kim', :]

array([[64, 28, 20, 42]])

In [98]:
# 요소가 Kim  또는 Park인 행의 데이터만 추출
data[(names == 'Kim') | (names == 'Park'), :]

array([[64, 28, 20, 42],
       [ 6, 12,  0,  0]])

In [99]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [101]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

##### Numpy 함수

###### 하나의 array 연산

In [102]:
arr1 = np.random.randint(-100, 100, size = (4, 3))
arr1

array([[-92, -72, -49],
       [ 72,  41,  11],
       [ 10,  87,  64],
       [-47, -95,  30]])

In [103]:
np.abs(arr1) # 절댓값
np.sqrt(arr1) # 제곱근
np.square(arr1) # 제곱
np.exp(arr1) # 지수함수
np.log(arr1) # 자연로그
np.log10(arr1) # 상용로그
np.log2(arr1) # 밑이 2인 로그

C:\Users\rproject\AppData\Local\Temp\ipykernel_20168\3763845832.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1) # 제곱근
C:\Users\rproject\AppData\Local\Temp\ipykernel_20168\3763845832.py:5: RuntimeWarning: invalid value encountered in log
  np.log(arr1) # 자연로그
C:\Users\rproject\AppData\Local\Temp\ipykernel_20168\3763845832.py:6: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1) # 상용로그
C:\Users\rproject\AppData\Local\Temp\ipykernel_20168\3763845832.py:7: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1) # 밑이 2인 로그


array([[       nan,        nan,        nan],
       [6.169925  , 5.357552  , 3.45943162],
       [3.32192809, 6.4429435 , 6.        ],
       [       nan,        nan, 4.9068906 ]])

In [104]:
np.sign(arr1) # 부호 계산

array([[-1, -1, -1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [-1, -1,  1]])

In [105]:
np.ceil(arr1) # 소수 첫째 자리에서 올림
np.floor(arr1) # 소수 첫째 자리에서 내림

array([[-92., -72., -49.],
       [ 72.,  41.,  11.],
       [ 10.,  87.,  64.],
       [-47., -95.,  30.]])

In [106]:
np.isnan(arr1) # NaN : Ture / not NaN : False
np.isnan(np.log(arr1))

C:\Users\rproject\AppData\Local\Temp\ipykernel_20168\2288391087.py:2: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(arr1))


array([[ True,  True,  True],
       [False, False, False],
       [False, False, False],
       [ True,  True, False]])

In [107]:
np.isinf(arr1) # 무한대 : True, not 무한대 : False

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [108]:
np.cos(arr1) # 삼각함수 (cos, cosh, sin, sinh, tan, tanh)

array([[-0.62644445, -0.96725059,  0.30059254],
       [-0.96725059, -0.98733928,  0.0044257 ],
       [-0.83907153,  0.56975033,  0.39185723],
       [-0.99233547,  0.73017356,  0.15425145]])

###### 두 개의 array 연산

In [109]:
arr2 = np.random.randint(-100, 100, size = (4, 3))

In [113]:
# 동일한 위치끼리 연산
np.multiply(arr1, arr2) # 곱하기
np.add(arr1, arr2) # 더하기
np.subtract(arr1, arr2) # 뺴기
np.divide(arr1, arr2) # 나누기

array([[-1.61403509,  0.75      ,  0.77777778],
       [-2.76923077, -1.05128205,  0.15068493],
       [-0.14925373,  8.7       , -0.90140845],
       [-0.6025641 , -1.72727273,  0.65217391]])

In [114]:
# 동일한 위치끼리 비교
np.maximum(arr1, arr2)
np.minimum(arr1, arr2)

array([[-92, -96, -63],
       [-26, -39,  11],
       [-67,  10, -71],
       [-47, -95,  30]])

###### 통계 함수

- axis 인자 값 지정
    - axis = 0 : 행 / axis = 1 : 열

In [115]:
np.sum(arr1) # 전체 성분 합
np.sum(arr1, axis = 1) # 열 별 합
np.sum(arr1, axis = 0) # 행 별 합

array([-57, -39,  56])

In [116]:
np.mean(arr1) # 전체 성분 평균
np.mean(arr1, axis = 0) # 행 별 평균

array([-14.25,  -9.75,  14.  ])

In [117]:
np.std(arr1) # 전체 성분 표준편차
np.var(arr1) # 전체 성분 분산
np.min(arr1, axis = 1) # 열 별 최소값
np.max(arr1) # 전체 성분 최대값

87

In [118]:
# 전체 성분 중, 조건이 위치한 "인덱스" 반환
np.argmin(arr1) # axis = none -> 1차원 배열로 위치 파악
np.argmax(arr1)

7

In [119]:
np.argmax(arr1, axis = 0) # 행 별 최대값

array([1, 2, 2], dtype=int64)

In [120]:
np.where(arr1 > 0) # 조건 만족 인덱스

(array([1, 1, 1, 2, 2, 2, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 2], dtype=int64))

In [121]:
np.cumsum(arr1) # 누적값
np.cumsum(arr1, axis = 1)

np.cumprod(arr1) # 누적곱

array([        -92,        6624,     -324576,   -23369472,  -958148352,
       -1949697280,  1977863680,   275448320,   448823296,   380141568,
       -1753710592, -1071710208])

where 함수를 이용하여 특정 조건에 맞는 값을, 다른 값으로 변환 가능

In [122]:
x = np.array([5, 4, 3, 2, 1, 0])

In [124]:
np.where(x >= 3)
x[np.where(x >= 3)]

array([5, 4, 3])

In [125]:
## 값이 3보다 크거나 같으면 3으로 변환, 아니라면 값 유지
np.where(x >= 3, 3, x)

array([3, 3, 3, 2, 1, 0])

In [126]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [127]:
np.where(x >= 6)
# 행과 열의 인덱스로 표시
# 첫번째 array가 행, 두번째 array가 열

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [129]:
np.where(x >= 6, 0, x)

array([[1, 2, 3, 4],
       [5, 0, 0, 0],
       [0, 0, 0, 0]])

In [128]:
ids, cols = np.where(x >= 6)
print(ids, cols)

[1 1 1 2 2 2 2] [1 2 3 0 1 2 3]


In [131]:
## 길이가 같은 리스트를, 인덱스별로 나누어 리스트로 반환
list(zip(ids, cols))

result = list(zip(ids, cols))
result[1][1]

2

###### 정렬 함수

In [134]:
## 열 기준 오름차순 (왼 -> 오)
np.sort(arr1)

## 행 기준 오름차순 (상 -> 하)
np.sort(arr1, axis = 0)

## 열 기준 내림차순 (왼 -> 오)
np.sort(arr1)[:, ::-1]

## 행 기준 내림차순 (상 -> 하)
np.sort(arr1, axis = 0)[::-1]

array([[ 72,  87,  64],
       [ 10,  41,  30],
       [-47, -72,  11],
       [-92, -95, -49]])