### 220628

In [2]:
import platform
print(platform.python_version())

3.10.5


In [3]:
import os
print(os.getcwd())

/Users/having/Desktop/Machine Learning/dachungcam/1week


#### Data Type

In [4]:
a = 1
b = 1.2345
c = 3 + 4j

# 변수의 타입 확인
type(a)
type(b)
type(c)

complex

In [5]:
d = a + b + c
d

(5.2345+4j)

##### Str Type

In [6]:
sa = 'Hello Bigdata'
print(sa)

sb = "Hello Bigdata"
print(sb)

sc = """Hello Bigdata"""
print(sc)

sd = '''Hello Bigdata'''
print(sd)

se = 'and Cheer up!'
print(se)

Hello Bigdata
Hello Bigdata
Hello Bigdata
Hello Bigdata
and Cheer up!


In [7]:
print(sd + se)

Hello Bigdataand Cheer up!


In [8]:
a = "="
print(a)
print(a * 50)

=


In [9]:
# 문자열 길이
len(a)
len(se)
len(a * 50)

50

문자열 인덱싱

In [10]:
a = 'this is a string'

print(a)
print(a[2])
print(a[0])
print(a[-1])
print(a[5])
print(a[4])

this is a string
i
t
g
i
 


문자열 슬라이싱

- 끝번호 값은 제외하고 출력

In [11]:
b = '20200722Wed'

print(b)
print(b[0:4])
print(b[4:6])
print(b[:8])
print(b[8:])
print(b[:])
print(b[:-5])

20200722Wed
2020
07
20200722
Wed
20200722Wed
202007


문자열 수정

In [12]:
a = 'this is a string'
a[10:] = 'rope'

TypeError: 'str' object does not support item assignment

In [13]:
b = 'robe'
a[:10] + b

'this is a robe'

In [14]:
# 문자 변경
c = a.replace('string', 'rope')
print(c)

this is a rope


문자열 format

In [15]:
a = 11

# %d 숫자(정수)
"a equals %d." %3
"a equals %d." %a

'a equals 11.'

In [16]:
b = -22
"vars are %d and %d." %(a, b)

# %s 문자("" 꼭 넣어주기)
"I have %s children." %"three"
"vars are %s and %s." %(a, b)

"vars are %s and %s" %(3.14, 5)

# %숫자s 자리수만큼 공백 오른쪽 정렬 (-는 왼쪽 정렬)
"%10s" %"Good"
"%-10s" %"Good"

# 소수 자리수 출력
"%.5f" %3.141592
"%20.5f" %3.141592 # 전체 20자리 공간에서 오른쪽 정렬 소수점 5자리

'             3.14159'

문자열 함수들

In [17]:
a = "Korean culture"

a.count('u')

a.find('u') # 문자 위치
a.find('K')
a.find('k') # -1 : 해당 문자 없음

a.index('u')
# a.index('k')

",".join('Korean culture') # 문자 사이 구분

a.upper()
a.lower()


'korean culture'

In [18]:
b = '     Korean cultrue   '

# 공백 제거
b.strip()
b.lstrip()
b.rstrip()


'     Korean cultrue'

In [19]:
a.replace("Korean", "American")
a.split()

['Korean', 'culture']

In [20]:
c = "Korean & American"
c.split("&")

['Korean ', ' American']

##### Boolean Type

In [21]:
d = True
type(d)

e = False

d and e
d or e
6 == 6
6 > 4
not d

# 문자열/리스트/튜플/딕셔너리가 비워져있으면 F
bool("ABC")
bool("")
bool([1, 2, 3])

# 0이면 F, 1이면 T
bool(0)
bool(1)

True

##### List Type

In [22]:
a = []
b = [1, 2, 3, 4, 5]
c = ['red', 'blue', 'yellow']
d = [1, 2, 'red', 'blue']
e = [1, 2, ['red', 'blue']]

print(a)
print(b)
print(c)
print(d)
print(e)

[]
[1, 2, 3, 4, 5]
['red', 'blue', 'yellow']
[1, 2, 'red', 'blue']
[1, 2, ['red', 'blue']]


리스트 인덱싱

In [23]:
b[0]
b[0] + b[2]
b[-1]

5

In [24]:
a = [1, 2, 3, 4, 5, ['a', 'b', 'c', 'd'], 7, 8, 9]

print(a)

a[0]
a[-1]
a[5]
a[5][2]

[1, 2, 3, 4, 5, ['a', 'b', 'c', 'd'], 7, 8, 9]


'c'

리스트 슬라이싱

In [25]:
b = [1, 2, 3, 4, 5]
b[0:4]

c = "12345"
c[0:4]

b[:3]
b[3:]

a[0:6]
a[0:6:1] # 한 자리마다 출력
a[0:6:2] # 두 자리마다 출력
a[0:6:3] # 세 자리마다 출력

a[5]
a[5][:2]

['a', 'b']

리스트 연산

In [26]:
a = [1, 2, 3, 4]
b = [6, 7, 8, 9]

a + b
a * 2

len(a)

4

In [27]:
k = [12345678]
len(k)

m = '12345678'
len(m)

c = 'good'
# b + c

c = ['good']
b + c

[6, 7, 8, 9, 'good']

In [28]:
a[3] = 9
print(a)

n = '1234'
n[3]
n[3] = '9' # 문자열 수정 X

[1, 2, 3, 9]


TypeError: 'str' object does not support item assignment

리스트 연산 함수

In [29]:
a = [1, 2, 3, 4, [a, b, c]]
b = [6, 7, 8, 9]

len(a)
# sum(a)
sum(b)
max(b)
min(b)

6

In [30]:
del(b[0]) #b[0] 삭제
print(b)

b = [6, 7, 8, 9]
del b[:3]
print(b)

str(b[0]) # 숫자형 -> 문자형 변경

[7, 8, 9]
[9]


'9'

In [31]:
b = ['6', '7', '8', '9']

b.append('10') # 기존 리스트에 추가
print(b)

b.append(['11', '12'])
print(b)

['6', '7', '8', '9', '10']
['6', '7', '8', '9', '10', ['11', '12']]


In [32]:
c = ['6', '9', '8', '7']
print(c)

c.sort()
print(c)

['6', '9', '8', '7']
['6', '7', '8', '9']


In [33]:
d = ['x', 'z', 'y']

d.sort()
print(d)

['x', 'y', 'z']


In [34]:
c = ['6', '9', '8', '7']
c.reverse() # 역순으로 변환
print(c)

c.index('9')
# c.index('5')

c.insert(4, '10') # 4번 인덱스에 10 추가
print(c)

c.insert(0, '5')
print(c)

['7', '8', '9', '6']
['7', '8', '9', '6', '10']
['5', '7', '8', '9', '6', '10']


In [35]:
e = ['3', '4', '3', '4', '5']

e.remove('4')
print(e)

e.remove('4')
print(e)

e.pop() # 마지막 요소 보여준 후, 삭제
print(e)

e.pop(1) # 1번 인덱스 요소 삭제
print(e)

e.pop(0)
print(e)

['3', '3', '4', '5']
['3', '3', '5']
['3', '3']
['3']
[]


In [36]:
c = [6, 6, 6, 6, 6, 7, 8, 9]

c.count(6)
c.extend([4, 5]) # 요소 추가, 입력은 리스트만 가능
print(c)

c.append([4, 5])
print(c)

[6, 6, 6, 6, 6, 7, 8, 9, 4, 5]
[6, 6, 6, 6, 6, 7, 8, 9, 4, 5, [4, 5]]


##### Tuple Type

- 리스트는 대괄호, 튜플은 소괄호 사용
- 리스트는 수정 가능, 튜플은 수정 불가능
- 한 개의 요소만 갖는 경우, 마지막에 콤마(,) 필요 -> 그렇지 않으면 정수 타입 생성
- 값이 자주 변경되면 리스트, 항상 변하지 않으면 튜플

In [37]:
a = tuple()
a = ()
type(a)

b = (1,)
type(b)

c = (1, 2, 3)
type(c)

d = 1, 2, 3 # 괄호 생략 가능
type(d)

e = 1, 2, ('ab', 'cd'), 3, 4
type(e)

tuple

In [38]:
e[0]

# 튜플은 수정/변경 불가
# del e[0]
# e.remove[1]

e[:]

c + e
c * 2
len(c)

x, y, z = (1, 2, 3)
print(x, y, z)
print(x)

1 2 3
1


##### Dict Type

- key와 value를 한 쌍으로 가지고 있음

In [39]:
a = {'gender':'Female', 'age':30, 'name':'Kristina'}
type(a)

# key 값을 입력하면, 그에 해당하는 value 반환
a['gender']
a['age']

# a[0]
a['Kristina'] # value 값만으로는 반환하지 않음

KeyError: 'Kristina'

In [40]:
b = {1:'good'}
print(b)

c = {'a':[1, 3, 5]}
print(c)

d = {'a':(1, 3, 5)}
print(d)

{1: 'good'}
{'a': [1, 3, 5]}
{'a': (1, 3, 5)}


In [41]:
# key 자리에 리스트 사용 X
# c = {[1, 3, 5 : 'a']}

# 튜플 사용 O
d = {(1, 3, 5) : 'a'}

In [42]:
a = {'gender' : 'Femal'}
a['age'] = 30 # key value 추가
print(a)

a['name'] = 'Kristina'
print(a)

a['a'] = [1, 3, 5]
print(a)

{'gender': 'Femal', 'age': 30}
{'gender': 'Femal', 'age': 30, 'name': 'Kristina'}
{'gender': 'Femal', 'age': 30, 'name': 'Kristina', 'a': [1, 3, 5]}


In [43]:
# key와 value 한 쌍이 같이 삭제
del a['a']
print(a)

del a['name']
print(a)

{'gender': 'Femal', 'age': 30, 'name': 'Kristina'}
{'gender': 'Femal', 'age': 30}


In [44]:
a = {'gender':'Female', 'age':30, 'name':'Kristina'}

a.keys()
list(a.keys())

a.values()
a.items()

a.clear() # 딕셔너리 내 모든 요소 삭제
print(a)

{}


In [45]:
a = {'gender':'Female', 'age':30, 'name':'Kristina'}

a.get('gender')
a.get('height', '?') # key가 딕셔너리 내에 값이 없을 때, ?로 표현

# 값이 있으면 T, 없으면 F
'gender' in a
'height' in a

False

### 220629

#### 연산

##### 수치 연산

In [46]:
2 + 3
3 - 2
2 * 3
3.14 ** 2 # 제곱승
2 ** .5
5 / 2
5 // 2 # 몫
5 % 2 # 나머지

1

In [47]:
a = 6
b = 4

a + b
a - b
a ** b
a / b
a // b
a % b

2

##### 대입 연산

In [48]:
a = 20

a += 5
print(a)

a -= 10
print(a)

a += 2
print(a)

a /= 3
print(a)

25
15
17
5.666666666666667


In [49]:
a = 3
b = 2

a += 2 + b
print(a)

a += b - 5
print(a)

7
4


##### 비교 연산

In [50]:
a = 95

a == 90
a != 90
a > 90
a < 90
a >= 90
a <= 90
a >= 90 and a <= 100
90 <= a <= 100
100 <= a <= 110
70 <= a <= 80

False

##### 논리연산

In [51]:
a = True
b = False

a and b
a and a
b and b

a or b
a or a
b or b

# 반대되는 논리 연산
not a
not (a and b)

True

##### 구성원 연산

In [52]:
a = [1, 2, 'Hello Data']

1 in a
a not in a
3 in a
3 not in a


b = {'a':1, 'b':2, 'c':3}

'a' in b
'k' in b
1 in b # key 값에 없음

False

##### 활용

In [53]:
a = [
{'num':'1', 'name':'김철수', 'kor':90, 'eng' : 80, 'math':85, 'total':0, 'avg':0.0},
{'num':'2', 'name':'박민주', 'kor':90, 'eng' : 85, 'math':90, 'total':0, 'avg':0.0},
{'num':'3', 'name':'박영호', 'kor':80, 'eng' : 80, 'math':80, 'total':0, 'avg':0.0}]

a[0]
a[0]['total']
a[0]['total'] = 1 # total의 value 1로 지정
a[0]

{'num': '1',
 'name': '김철수',
 'kor': 90,
 'eng': 80,
 'math': 85,
 'total': 1,
 'avg': 0.0}

In [54]:
# 학생별 합계 구하기
a[0]['total'] = a[0]['kor'] + a[0]['eng'] + a[0]['math']
a[1]['total'] = a[1]['kor'] + a[1]['eng'] + a[1]['math']
a[2]['total'] = a[2]['kor'] + a[2]['eng'] + a[2]['math']

a[0]['total']
a[1]['total']
a[2]['total']

240

In [55]:
# 학생별 평균 구하기
a[0]['avg'] = a[0]['total']/3
a[1]['avg'] = a[1]['total']/3
a[2]['avg'] = a[2]['total']/3

print(a)

[{'num': '1', 'name': '김철수', 'kor': 90, 'eng': 80, 'math': 85, 'total': 255, 'avg': 85.0}, {'num': '2', 'name': '박민주', 'kor': 90, 'eng': 85, 'math': 90, 'total': 265, 'avg': 88.33333333333333}, {'num': '3', 'name': '박영호', 'kor': 80, 'eng': 80, 'math': 80, 'total': 240, 'avg': 80.0}]


In [56]:
# 학급평균 구하기
b = (a[0]['total'] + a[1]['total'] + a[2]['total']) / 3
print(b)

253.33333333333334


#### 조건문

##### if문

In [57]:
x = 5
if x < 10 :
    a = 1

a

1

##### if-else문

In [58]:
if True :
    print('참입니다')
else :
    print('거짓입니다')

if False :
    print('참입니다')
else :
    print('거짓입니다')

참입니다
거짓입니다


In [59]:
a = 1000

if a > 5000 :
    print('택시를 탑니다')
else :
    print('버스를 타야합니다')

if a <= 5000 :
    print('택시를 탑니다')
else :
    print('버스를 타야합니다')

버스를 타야합니다
택시를 탑니다


In [186]:
# input 사용자에게 입력받은 값을 변수에 저장
# float 실수형으로 변환 / int 정수형으로 변환 / str 문자형으로 변환

grade = float(input('총 평점을 입력해 주세요 : '))

if grade >= 4.3 :
    print('당신은 장학급 수여 대상자입니다')
    print('축하합니다')

당신은 장학급 수여 대상자입니다
축하합니다


In [187]:
data = int(input('숫자를 입력하시오 : '))

if data % 2 == 0 :
    print('입력된 값은 짝수입니다.')
else :
    print('입력된 값은 홀수입니다.')

입력된 값은 짝수입니다.


##### if-elif-els문

- 조건이 여러개일 때

In [62]:
x = 5

if x < 10 :
    a = 1
elif 10 <= x and x < 20 :
    a = 2
else :
    a = 3

a

1

##### 중첩 if문

In [188]:
age = int(input('나이를 입력하세요 : '))
height = int(input('키를 입력하세요 : '))

if age >= 40 :
    if height >= 170 :
        print('키가 보통 이상입니다')
    else :
        print('키가 보통입니다')
else :
    if height >= 175 :
        print('키가 보통 이상입니다')
    else :
        print('키가 보통입니다')

키가 보통입니다


##### 간략한 if-else문

- if문과 else문 뒤에 수행할 문장이 한 줄인 경우
- (참일 경우 실행문) if (조건문) else (거짓일 경우 실행문)

In [64]:
score = 80

if score >= 70 :
    a = "good"
else :
    a = "bad"

a = "good" if score >= 70 else "bad"

a

'good'

#### 반복문

##### for문

In [65]:
for a in [1, 2, 3] :
    print(a)

for a in [[1, 3], [5, 7], [9]] :
    print(a)

for a in [(1, 3), {5, 7}, 9] :
    print(a)

1
2
3
[1, 3]
[5, 7]
[9]
(1, 3)
{5, 7}
9


In [66]:
(a, b) = (1, 2)
print(a)
print(b)
print(a, b)

1
2
1 2


In [67]:
for (a, b) in [(1, 2), (3, 4), (5, 6)] :
    print(a + b)

3
7
11


In [68]:
a = "Hello!"
b = ["Hello!", "Data"]
c = (1, 2, 3)

for x in a :
    print(x)

for x in a :
    print(x, end = "")

H
e
l
l
o
!
Hello!

In [69]:
for x in b :
    print(x)

for x in c :
    print(x)

Hello!
Data
1
2
3


In [70]:
d = {'circle':2, 'rectangle':3, 'line':1}
e = {'red', 'green', 'blue', 'red'}

# dict는 key 값만 출력
for x in d :
    print(x)

# 순서가 없고, 중복 허용 X
for x in e :
    print(x)

circle
rectangle
line
blue
green
red


range

In [71]:
list(range(3, 31, 3))

result = 0

for i in list(range(1, 11, 2)) :
    result = result + 3
    print(result)

3
6
9
12
15


In [72]:
lst = [1, 2, 3, 4, 5]
result = [ ]

for num in lst :
    result.append(num * 3)

print(result) 

[3, 6, 9, 12, 15]


In [73]:
lst = [1, 2, 3, 4, 5]
result = [num * 3 for num in lst]
print(result)

[3, 6, 9, 12, 15]


In [74]:
result = [num * 3 for num in lst if num % 2 == 0]
print(result)

[6, 12]


이중 for문

In [75]:
# print 구문의 위치에 따라서 결과값이 달라짐
for a in range(2, 10) :
    for b in range(1, 10) :
        print(a * b, end = " ")
    print(' ')

for a in range(2, 10) :
    for b in range(1, 10) :
        print(a * b)
    print(' ')

2 4 6 8 10 12 14 16 18  
3 6 9 12 15 18 21 24 27  
4 8 12 16 20 24 28 32 36  
5 10 15 20 25 30 35 40 45  
6 12 18 24 30 36 42 48 54  
7 14 21 28 35 42 49 56 63  
8 16 24 32 40 48 56 64 72  
9 18 27 36 45 54 63 72 81  
2
4
6
8
10
12
14
16
18
 
3
6
9
12
15
18
21
24
27
 
4
8
12
16
20
24
28
32
36
 
5
10
15
20
25
30
35
40
45
 
6
12
18
24
30
36
42
48
54
 
7
14
21
28
35
42
49
56
63
 
8
16
24
32
40
48
56
64
72
 
9
18
27
36
45
54
63
72
81
 


for문 안에 조건문(if-else)

In [76]:
Score = [100, 7, 75, 32]
num = 0

for a in Score :
    num += 1
    if a >= 70 :
        print('%d번 합격' %num)
    else :
        print('%d번 불합격' %num)

1번 합격
2번 불합격
3번 합격
4번 불합격


##### While문

In [77]:
i = 1

while i < 10 :
    result = 2 * i
    print(result)
    i += 1

2
4
6
8
10
12
14
16
18


In [78]:
a = 1
b = 0

while a <= 100 :
    b = b + a
    a = a + 1
    
print('1부터 100까지의 합은 : ', b)

1부터 100까지의 합은 :  5050


break

- 특정 조건을 만족하면 반복문 강제 종료

In [79]:
a = 1
b = 0

while a <= 100 :
    b = b + a
    a = a + 1
    
    if b > 3000 :
        break


print('1부터 100까지의 합은 : ', b)

1부터 100까지의 합은 :  3003


In [80]:
result = [ ]

for i in range(1, 6) :
    for j in range(1, 11) :
        k = i * j
        result_temp = [i, j, k]
        
        if k > 10 :
            break
        result.append(result_temp)

print(result)

[[1, 1, 1], [1, 2, 2], [1, 3, 3], [1, 4, 4], [1, 5, 5], [1, 6, 6], [1, 7, 7], [1, 8, 8], [1, 9, 9], [1, 10, 10], [2, 1, 2], [2, 2, 4], [2, 3, 6], [2, 4, 8], [2, 5, 10], [3, 1, 3], [3, 2, 6], [3, 3, 9], [4, 1, 4], [4, 2, 8], [5, 1, 5], [5, 2, 10]]


continue

- 해당 step을 실행하지 않고 건너뜀

In [81]:
Score = [100, 7, 75, 32]
num = 0

for a in Score :
    num += 1
    
    if a < 70 :
        continue
    else :
        print('%d번 합격' %num)

1번 합격
3번 합격


#### 사용자 정의 함수

In [82]:
def square(x) :
    return x * x

square(5)

25

In [83]:
def even_or_odd(n) :
    if n % 2 == 0 :
        print("even")
        return
    print("odd")

even_or_odd(3)
even_or_odd(4)

odd
even


In [84]:
def Function_1(a, b) :
    x = a + 5
    y = b * 3
    z = x + y
    return z

Function_1(1, 5)
Function_1(a = 1, b = 5)

21

- 입력변수가 몇 개인지 모를 때, 매개변수 앞에 `*` 추가

In [85]:
def add_many(*args) :
    result = 0

    for i in args :
        result += i
    return result

add_many(1, 2, 3)
add_many(1, 2, 3, 4)

10

In [86]:
def add_many(choice, *args) :
    result = 0

    if choice == "good" :
        for i in args :
            result += i
    elif choice == "bad" :
        for i in args :
            result -= i
    return result

add_many("good", 1, 2, 3, 4, 5, 6)
add_many("bad", 1, 2, 3, 4, 5, 6)

-21

- 조건을 만족하면, return 함수로 함수 빠져나옴

In [87]:
def say_nick(nick) :
    if nick == "바보" :
        return
    print("나의 별명은 %s 입니다." %nick)

say_nick("바보")
say_nick("천재")

나의 별명은 천재 입니다.


- 매개변수에 초기 값 입력

In [88]:
def say_myself(name, old, man = True) :
    print("나의 이름은 %s 입니다." %name)
    print("나이는 %d살입니다." %old)

    if man :
        print("남자입니다.")
    else :
        print("여자입니다.")

say_myself("민주", 41)

나의 이름은 민주 입니다.
나이는 41살입니다.
남자입니다.


In [89]:
a = 1

def vartest(a) :
    a += 1

vartest(a)

print(a)

1


In [90]:
a = 1

def vartest(a) :
    a += 1
    return a

a = vartest(a)
print(a)

2


In [91]:
a = 1

def vartest() :
    global a
    a += 1

vartest()
print(a)

2


### 220630

##### Numpy

In [92]:
# pip install numpy

In [222]:
import numpy as np

##### 배열과 리스트 비교

- 배열은 모든 원소가 같은 자료형이어야 하고, 리스트는 각각의 원소가 다른 자료형이 될 수 있음
- 배열은 원소의 갯수를 변경할 수 없음

In [94]:
a = np.array(([1, 2], [3, 4])) # 배열
b = [[1, 2], [3, 4]] # 리스트

a
b

a[1, 1]
b[1][1]

4

1차원 배열

In [95]:
data1 = [1, 2, 3, 4, 5]
data1

data2 = [1, 2, 3, 3.5, 4]
data2

# numpy를 이용하여 array 정의
arr1 = np.array(data1)
arr1

# array의 형태(크기) 확인
arr1.shape


arr2 = np.array([1, 2, 3, 4, 5])
arr2

arr2.shape

# array의 자료형
arr2.dtype


arr3 = np.array(data2)
arr3

arr3.shape
arr3.dtype

dtype('float64')

2차원 배열

In [96]:
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr4

arr4.shape

(4, 3)

3차원 배열

In [97]:
arr5 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
type(arr5)
arr5.shape

(2, 4, 3)

기타 배열

- np.zeros : 모든 요소가 0인 array
- np.ones : 모든 요소가 1인 array
- np.arange : 1씩 증가하는 1차원 array
- np.full : 특정 값으로채움
- np.eye : 단위 행렬
- np.empty : 초기화되지 않은 값으로 배열 생성

In [98]:
np.zeros(10)
np.zeros((3, 5))

np.ones(9)
np.ones((2, 10))

np.arange(10) # 0부터 9까지
np.arange(3, 10) # 3부터 9까지

np.full((2, 2), 7) # 2*2 array에 7로 full

np.eye(4)

np.empty((4, 2)) # 메모리 초기화되지 않아, 예상치 못한 garbage value가 포함

array([[2.00000000e+000, 2.00000000e+000],
       [1.97626258e-323, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [1.72723383e-077, 5.56268614e-309]])

In [99]:
# 동일한 구조와 데이터 형태를 유지한 상태로, 각 "0, 1, 빈 배열" 반환
a = np.arange(1, 10).reshape(3, 3)
a

np.zeros_like(a)
np.ones_like(a)
np.empty_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##### Array 연산

- 크기가 동일한 array끼리 연산
- 같은 위치에 있는 요소들끼리 연산

In [100]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1.shape

arr2 = np.array([[10, 11, 12], [13, 14, 15]])
arr2.shape

arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [101]:
# 브로드 캐스트 - 크기가 다른 array 연산 가능
arr1.shape

arr3 = np.array([10, 11, 12])
arr3.shape

arr1 + arr3
arr1 * 10
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

Array의 인덱싱

In [102]:
arr1 = np.arange(10)

arr1[0]
arr1[3]
arr1[3:9]
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
# 다차원 배열에서 각 차원에 대해 가능

arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr2[0, 0]
arr2[2, :]
arr2[2, 3]
arr2[:, 3]
arr2[[2, 0, 1], :] # 행 순서 변경

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [104]:
# boolean 인덱싱 (마스크) - 원하는 행 또는 열의 값만 추출 (TRUE 값)

data = np.random.randn(8, 4) # 가우시안 정규분포
data

data = np.random.randint(0, 100, size= (8, 4))
data

type(data)
data.shape

(8, 4)

In [105]:
data[:, 0] < 50 # boolean 값
data[data[:, 0] < 50, :]
data[data[:, 0] < 50, 2:4]
data[data[:, 0] < 50, 2:4] = 0
data

array([[90, 69, 71, 43],
       [ 3, 91,  0,  0],
       [96, 13, 94, 45],
       [93, 82, 63, 65],
       [88, 71, 79, 16],
       [ 3, 72,  0,  0],
       [98, 93, 60, 40],
       [37, 45,  0,  0]])

In [106]:
arr2[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [107]:
names = np.array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park', 'Beomwoo'])

names
names.shape

(8,)

In [108]:
names[0, ]
names[4, ]

'Lee'

In [109]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
names_Beomwoo_mask

array([ True,  True, False, False, False,  True, False,  True])

In [110]:
data[names_Beomwoo_mask, :]

array([[90, 69, 71, 43],
       [ 3, 91,  0,  0],
       [ 3, 72,  0,  0],
       [37, 45,  0,  0]])

In [111]:
# 요소가 Kim인 행의 데이터만 꺼내기
names == 'Kim'

data[names == 'Kim', :]

array([[96, 13, 94, 45]])

In [112]:
# 요소가 Kim  또는 Park인 행의 데이터만 추출
data[(names == 'Kim') | (names == 'Park'), :]

array([[96, 13, 94, 45],
       [98, 93, 60, 40]])

In [113]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [115]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

##### Numpy 함수

하나의 array 연산

In [116]:
arr1 = np.random.randint(-100, 100, size = (4, 3))
arr1

array([[ 86, -92, -59],
       [-44, -75, -28],
       [-18, -50, -82],
       [ 91,  56,  30]])

In [117]:
np.abs(arr1) # 절댓값
np.sqrt(arr1) # 제곱근
np.square(arr1) # 제곱
np.exp(arr1) # 지수함수
np.log(arr1) # 자연로그
np.log10(arr1) # 상용로그
np.log2(arr1) # 밑이 2인 로그

/var/folders/zk/0y17q3bj77xdvtsp77b9vq100000gn/T/ipykernel_10037/3763845832.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1) # 제곱근
/var/folders/zk/0y17q3bj77xdvtsp77b9vq100000gn/T/ipykernel_10037/3763845832.py:5: RuntimeWarning: invalid value encountered in log
  np.log(arr1) # 자연로그
/var/folders/zk/0y17q3bj77xdvtsp77b9vq100000gn/T/ipykernel_10037/3763845832.py:6: RuntimeWarning: invalid value encountered in log10
  np.log10(arr1) # 상용로그
/var/folders/zk/0y17q3bj77xdvtsp77b9vq100000gn/T/ipykernel_10037/3763845832.py:7: RuntimeWarning: invalid value encountered in log2
  np.log2(arr1) # 밑이 2인 로그


array([[6.42626475,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [6.50779464, 5.80735492, 4.9068906 ]])

In [118]:
np.sign(arr1) # 부호 계산

array([[ 1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 1,  1,  1]])

In [119]:
np.ceil(arr1) # 소수 첫째 자리에서 올림
np.floor(arr1) # 소수 첫째 자리에서 내림

array([[ 86., -92., -59.],
       [-44., -75., -28.],
       [-18., -50., -82.],
       [ 91.,  56.,  30.]])

In [120]:
np.isnan(arr1) # NaN : Ture / not NaN : False
np.isnan(np.log(arr1))

/var/folders/zk/0y17q3bj77xdvtsp77b9vq100000gn/T/ipykernel_10037/2288391087.py:2: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(arr1))


array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [121]:
np.isinf(arr1) # 무한대 : True, not 무한대 : False

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [122]:
np.cos(arr1) # 삼각함수 (cos, cosh, sin, sinh, tan, tanh)

array([[-0.38369844, -0.62644445, -0.77108022],
       [ 0.99984331,  0.92175127, -0.96260587],
       [ 0.66031671,  0.96496603,  0.9496777 ],
       [-0.99436746,  0.85322011,  0.15425145]])

두 개의 array 연산

In [123]:
arr2 = np.random.randint(-100, 100, size = (4, 3))

In [124]:
# 동일한 위치끼리 연산
np.multiply(arr1, arr2) # 곱하기
np.add(arr1, arr2) # 더하기
np.subtract(arr1, arr2) # 뺴기
np.divide(arr1, arr2) # 나누기

array([[-1.45762712, -1.37313433, -1.18      ],
       [ 0.62857143,  2.67857143,  0.28      ],
       [-0.25714286, -1.35135135, 82.        ],
       [-1.16666667, -1.43589744, -0.44117647]])

In [125]:
# 동일한 위치끼리 비교
np.maximum(arr1, arr2)
np.minimum(arr1, arr2)

array([[ -59,  -92,  -59],
       [ -70,  -75, -100],
       [ -18,  -50,  -82],
       [ -78,  -39,  -68]])

통계 함수

- axis 인자 값 지정
    - axis = 0 : 행 / axis = 1 : 열

In [126]:
np.sum(arr1) # 전체 성분 합
np.sum(arr1, axis = 1) # 열 별 합
np.sum(arr1, axis = 0) # 행 별 합

array([ 115, -161, -139])

In [127]:
np.mean(arr1) # 전체 성분 평균
np.mean(arr1, axis = 0) # 행 별 평균

array([ 28.75, -40.25, -34.75])

In [128]:
np.std(arr1) # 전체 성분 표준편차
np.var(arr1) # 전체 성분 분산
np.min(arr1, axis = 1) # 열 별 최소값
np.max(arr1) # 전체 성분 최대값

91

In [129]:
# 전체 성분 중, 조건이 위치한 "인덱스" 반환
np.argmin(arr1) # axis = none -> 1차원 배열로 위치 파악
np.argmax(arr1)

9

In [130]:
np.argmax(arr1, axis = 0) # 행 별 최대값

array([3, 3, 3])

In [131]:
np.where(arr1 > 0) # 조건 만족 인덱스

(array([0, 3, 3, 3]), array([0, 0, 1, 2]))

In [132]:
np.cumsum(arr1) # 누적값
np.cumsum(arr1, axis = 1)

np.cumprod(arr1) # 누적곱

array([                  86,                -7912,               466808,
                  -20539552,           1540466400,         -43133059200,
               776395065600,      -38819753280000,     3183219768960000,
         289672998975360000, -2225056131089391616,  7035292362156457984])

where 함수를 이용하여 특정 조건에 맞는 값을, 다른 값으로 변환 가능

In [133]:
x = np.array([5, 4, 3, 2, 1, 0])

In [134]:
np.where(x >= 3)
x[np.where(x >= 3)]

array([5, 4, 3])

In [135]:
## 값이 3보다 크거나 같으면 3으로 변환, 아니라면 값 유지
np.where(x >= 3, 3, x)

array([3, 3, 3, 2, 1, 0])

In [136]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [137]:
np.where(x >= 6)
# 행과 열의 인덱스로 표시
# 첫번째 array가 행, 두번째 array가 열

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [138]:
np.where(x >= 6, 0, x)

array([[1, 2, 3, 4],
       [5, 0, 0, 0],
       [0, 0, 0, 0]])

In [139]:
ids, cols = np.where(x >= 6)
print(ids, cols)

[1 1 1 2 2 2 2] [1 2 3 0 1 2 3]


In [140]:
## 길이가 같은 리스트를, 인덱스별로 나누어 리스트로 반환
list(zip(ids, cols))

result = list(zip(ids, cols))
result[1][1]

2

정렬 함수

In [141]:
## 열 기준 오름차순 (왼 -> 오)
np.sort(arr1)

## 행 기준 오름차순 (상 -> 하)
np.sort(arr1, axis = 0)

## 열 기준 내림차순 (왼 -> 오)
np.sort(arr1)[:, ::-1]

## 행 기준 내림차순 (상 -> 하)
np.sort(arr1, axis = 0)[::-1]

array([[ 91,  56,  30],
       [ 86, -50, -28],
       [-18, -75, -59],
       [-44, -92, -82]])

##### Pandas

In [142]:
# pip install pandas

In [143]:
import pandas as pd

pandas에서는 Series와 Data Frame 구조 사용

Series
- 어떠한 데이터 타입 보유 가능한 레이블링된 1차원 배열
- `pd.Series` 함수로 정의, list/numpy의 array가 인자로 입력

In [144]:
## series 정의
obj = pd.Series([4, 7, -5, 3])

obj # index와 values 동시 확인 가능
obj.values # value만 확인
obj.index # index만 확인

obj.dtypes # 자료형 확인

dtype('int64')

In [145]:
obj2 = pd.Series([4, 7, -5, 3], index = ["d", "b", "a", "c"]) # 인덱스 변경 가능
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [146]:
## dict 자료형을 series로 변경 가능
## dict의 key가 series의 index
sdata = {'Kim':35000, 'Beomwoo':67000, 'Joan':12000, 'Choi':4000}
obj3 = pd.Series(sdata)
obj3

Kim        35000
Beomwoo    67000
Joan       12000
Choi        4000
dtype: int64

In [147]:
## series 이름, index 이름 지정
obj3.name = 'Salary'
obj3.index.name = 'Names'
obj3

Names
Kim        35000
Beomwoo    67000
Joan       12000
Choi        4000
Name: Salary, dtype: int64

In [148]:
## index 변경
obj3.index = ['A', 'B', 'C', 'D']
obj3

A    35000
B    67000
C    12000
D     4000
Name: Salary, dtype: int64

DataFrame
- Series 객체를 모아둔, 2차원 테이블 구조를 가지는 자료형
- key value의 개수가 열(Columns)의 개수, list의 성분 개수는 행(index)의 개수

In [149]:
## DataFrame 정의
# DataFrame에 들어갈 데이터 정의는 dict 또는 array로 정의
data = {'name' : ['Beomwoo', 'Beomwoo', 'Beomwoo', 'Kim', 'Park'],
        'year' : [2013, 2014, 2015, 2016, 2015],
        'points' : [1.5, 1.7, 3.6, 2.4, 2.9]}

df = pd.DataFrame(data)
df

name  year  points
0  Beomwoo  2013     1.5
1  Beomwoo  2014     1.7
2  Beomwoo  2015     3.6
3      Kim  2016     2.4
4     Park  2015     2.9

In [150]:
df.index # 행 방향 index
df.columns # 열 방향 index
df.values # 값

array([['Beomwoo', 2013, 1.5],
       ['Beomwoo', 2014, 1.7],
       ['Beomwoo', 2015, 3.6],
       ['Kim', 2016, 2.4],
       ['Park', 2015, 2.9]], dtype=object)

In [151]:
## 각 index 이름 설정
df.index.name = 'Num'
df.columns.name = 'Info'
df

Info     name  year  points
Num                        
0     Beomwoo  2013     1.5
1     Beomwoo  2014     1.7
2     Beomwoo  2015     3.6
3         Kim  2016     2.4
4        Park  2015     2.9

In [152]:
## DataFrame 생성 시, columns와 index 설정 가능
df2 = pd.DataFrame(data, columns = ['year', 'name', 'points', 'penalty'],
                index = ['one', 'two', 'three', 'four', 'five'])
df2

year     name  points penalty
one    2013  Beomwoo     1.5     NaN
two    2014  Beomwoo     1.7     NaN
three  2015  Beomwoo     3.6     NaN
four   2016      Kim     2.4     NaN
five   2015     Park     2.9     NaN

In [153]:
df2.describe() # 수치형 value에 대한 통계값

year    points
count     5.000000  5.000000
mean   2014.600000  2.420000
std       1.140175  0.864292
min    2013.000000  1.500000
25%    2014.000000  1.700000
50%    2015.000000  2.400000
75%    2015.000000  2.900000
max    2016.000000  3.600000

DataFrame의 Attributes

In [154]:
from pandas import DataFrame as df

In [155]:
df_1 = df(data = np.arange(12).reshape(3, 4),
        index = ['r0', 'r1', 'r2'],
        columns = ['c0', 'c1', 'c2', 'c3'],
        dtype = 'int', copy = False)
df_1

c0  c1  c2  c3
r0   0   1   2   3
r1   4   5   6   7
r2   8   9  10  11

In [156]:
## 행/열 전치
df_1.T

## 행/열 이름 리스트로 반환
df_1.axes

## 데이터 형태
df_1.dtypes

## 차원(행/열 개수) 튜플로 반환
df_1.shape
df_1.shape[0]

## 원소 개수
df_1.size

## numpy 형태로 원소 반환
df_1.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [157]:
## DataFrame 조회
df_1.head(2)
df_1.tail(2)

c0  c1  c2  c3
r1   4   5   6   7
r2   8   9  10  11

동일한 형태의 여러 DataFrame 병합 - `pd.condat()`

In [189]:
from pandas import DataFrame as df

In [190]:
df_1 = pd.DataFrame({'A' : ['A0', 'A1', 'A2'],
                    'B' : ['B0', 'B1', 'B2'],
                    'C' : ['C0', 'C1', 'C2'],
                    'D' : ['D0', 'D1', 'D2']},
                    index = [0, 1, 2])

df_2 = pd.DataFrame({'A' : ['A3', 'A4', 'A5'],
                    'B' :['B3', 'B4', 'B5'],
                    'C' : ['C3', 'C4', 'C5'],
                    'D' : ['D3', 'D4', 'D5']},
                    index = [0, 1, 2])

In [191]:
## 위아래 병합 : axis = 0
df_12_axis0 = pd.concat([df_1, df_2])
df_12_axis0

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
0  A3  B3  C3  D3
1  A4  B4  C4  D4
2  A5  B5  C5  D5

In [192]:
df_3 = pd.DataFrame({'E' : ['A6', 'A7', 'A8'],
                    'F' : ['B6', 'B7', 'B8'],
                    'G' : ['C6', 'C7', 'C8'],
                    'H' : ['D6', 'D7', 'D8']},
                    index = [0, 1, 2])

In [193]:
## 좌우 병합 : axis = 1
df_13_axis1 = pd.concat([df_1, df_3], axis = 1)
df_13_axis1

A   B   C   D   E   F   G   H
0  A0  B0  C0  D0  A6  B6  C6  D6
1  A1  B1  C1  D1  A7  B7  C7  D7
2  A2  B2  C2  D2  A8  B8  C8  D8

In [194]:
df_4 = pd.DataFrame({'A' : ['A0', 'A1', 'A2'],
                    'B' : ['B0', 'B1', 'B2'],
                    'C' : ['C0', 'C1', 'C2'],
                    'E' : ['E0', 'E1', 'E2']},
                    index = [0, 1, 3])

In [195]:
## 합집합 병합 : join = 'outer'
df_14_outer = pd.concat([df_1, df_4], join = 'outer')
df_14_outer

A   B   C    D    E
0  A0  B0  C0   D0  NaN
1  A1  B1  C1   D1  NaN
2  A2  B2  C2   D2  NaN
0  A0  B0  C0  NaN   E0
1  A1  B1  C1  NaN   E1
3  A2  B2  C2  NaN   E2

In [196]:
## 교집합 병합 : join = 'inner'
df_14_inner = pd.concat([df_1, df_4], join = 'inner')
df_14_inner

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A0  B0  C0
1  A1  B1  C1
3  A2  B2  C2

In [197]:
df_left = df({'A' : ['A0', 'A1', 'A2', 'A3'],
            'B' : ['B0', 'B1', 'B2', 'B3']},
            index = ['K0', 'K1', 'K2', 'K3'])

df_right = df({'C' : ['C2', 'C3', 'C4', 'C5'],
            'D' : ['D2', 'D3', 'D4', 'D5']},
            index = ['K2', 'K3', 'K4', 'K5'])

In [198]:
## index 기준 left 병합
# merge
pd.merge(df_left, df_right,
        left_index = True, right_index = True,
        how = 'left')

# join
df_left.join(df_right, how = 'left')

A   B    C    D
K0  A0  B0  NaN  NaN
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2
K3  A3  B3   C3   D3

In [199]:
## index 기준 right 병합
# merge
pd.merge(df_left, df_right,
        left_index = True, right_index = True,
        how = 'right')

# join
df_left.join(df_right, how = 'right')

A    B   C   D
K2   A2   B2  C2  D2
K3   A3   B3  C3  D3
K4  NaN  NaN  C4  D4
K5  NaN  NaN  C5  D5

In [200]:
## index 기준 inner join
# merge
pd.merge(df_left, df_right,
        left_index = True, right_index = True,
        how = 'inner')

# join
df_left.join(df_right, how = 'inner')

A   B   C   D
K2  A2  B2  C2  D2
K3  A3  B3  C3  D3

In [201]:
## index 기준 outer join
# merge
pd.merge(df_left, df_right,
        left_index = True, right_index = True,
        how = 'outer')

# join
df_left.join(df_right, how = 'outer')

A    B    C    D
K0   A0   B0  NaN  NaN
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3   A3   B3   C3   D3
K4  NaN  NaN   C4   D4
K5  NaN  NaN   C5   D5

DataFrame 열 조작

In [202]:
data = {'names' : ['Kilho', 'Kilho', 'Kilho', 'Charies', 'Charies'],
        'year' : [2014, 2015, 2016, 2015, 2016],
        'points' : [1.5, 1.7, 3.6, 2.4, 2.9]}

df = pd.DataFrame(data, columns = ['year', 'names', 'points', 'penalty'],
                index = ['one', 'two', 'three', 'four', 'five'])

In [203]:
## 열 선택
df['year']
df.year
df[['year', 'points']]

year  points
one    2014     1.5
two    2015     1.7
three  2016     3.6
four   2015     2.4
five   2016     2.9

In [204]:
## 특정 열 선택 후, 값 대입
df['penalty'] = .5
df['penalty'] = [.1, .2, .3, .4, .5]

In [205]:
## 새로운 열 추가
df['zeros'] = np.arange(5)
df

year    names  points  penalty  zeros
one    2014    Kilho     1.5      0.1      0
two    2015    Kilho     1.7      0.2      1
three  2016    Kilho     3.6      0.3      2
four   2015  Charies     2.4      0.4      3
five   2016  Charies     2.9      0.5      4

In [206]:
## Series 추가 가능
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

df['debt'] = val
df

year    names  points  penalty  zeros  debt
one    2014    Kilho     1.5      0.1      0   NaN
two    2015    Kilho     1.7      0.2      1  -1.2
three  2016    Kilho     3.6      0.3      2   NaN
four   2015  Charies     2.4      0.4      3  -1.5
five   2016  Charies     2.9      0.5      4  -1.7

In [207]:
df['net_points'] = df['points'] - df['penalty']
df['high_points'] = df['net_points'] > 2.0
df

year    names  points  penalty  zeros  debt  net_points  high_points
one    2014    Kilho     1.5      0.1      0   NaN         1.4        False
two    2015    Kilho     1.7      0.2      1  -1.2         1.5        False
three  2016    Kilho     3.6      0.3      2   NaN         3.3         True
four   2015  Charies     2.4      0.4      3  -1.5         2.0        False
five   2016  Charies     2.9      0.5      4  -1.7         2.4         True

In [208]:
## 열 삭제
del df['high_points']
del df['net_points']
del df['zeros']
df

year    names  points  penalty  debt
one    2014    Kilho     1.5      0.1   NaN
two    2015    Kilho     1.7      0.2  -1.2
three  2016    Kilho     3.6      0.3   NaN
four   2015  Charies     2.4      0.4  -1.5
five   2016  Charies     2.9      0.5  -1.7

In [209]:
df.columns

Index(['year', 'names', 'points', 'penalty', 'debt'], dtype='object')

DataFrame 행 조작

- `df.loc["index명"]` : Series의 형태로 추출
- `.loc` 함수는, 행과 열 동시에 인덱스 가능
- `.loc[:, "column명"]` = `df["column명"]`

In [210]:
df[0:3] # 0~2행 출력
df['two':'four'] # two~four 행 출력

# 위 방법보다는, 다음의 방법 권장
df.loc['two']
df.loc['two':'four']
df.loc['two':'four', 'points']

two      1.7
three    3.6
four     2.4
Name: points, dtype: float64

In [211]:
df.loc[:, 'year']
df.loc[:, ['year', 'names']]
df.loc['three':'five', 'year':'penalty']

year    names  points  penalty
three  2016    Kilho     3.6      0.3
four   2015  Charies     2.4      0.4
five   2016  Charies     2.9      0.5

In [212]:
## 새로운 행 삽입
df.loc['six', :] = [2013, 'Jun', 4.0, .1, 2.1]
df

year    names  points  penalty  debt
one    2014.0    Kilho     1.5      0.1   NaN
two    2015.0    Kilho     1.7      0.2  -1.2
three  2016.0    Kilho     3.6      0.3   NaN
four   2015.0  Charies     2.4      0.4  -1.5
five   2016.0  Charies     2.9      0.5  -1.7
six    2013.0      Jun     4.0      0.1   2.1

In [213]:
df.iloc[3] # 3번째 행 추출
df.iloc[3:5, 0:2]
df.iloc[[0, 1, 3], [1, 2]]
df.iloc[:, 1:4]
df.iloc[1, 1]

'Kilho'

DataFrame boolean indexing

In [214]:
df['year'] > 2014 # Series 형태, mask 삭제
df.loc[df['year'] > 2014, :]
df.loc[df['names'] == 'Kilho', ['names', 'points']]

names  points
one    Kilho     1.5
two    Kilho     1.7
three  Kilho     3.6

In [215]:
## 조건이 여러개인 경우, & 연산자 이용
df.loc[(df['points'] > 2) & (df['points'] < 3), :]

## 새로운 값 대입
df.loc[df['points'] > 3, 'penalty'] = 0

### 220701

DataFrame 조작

- `pd.date_range("yyyymmdd", periods = 6)` : 날짜 데이터 생성
- Datetime64 데이터 형태로 구성된 index
- `periods = 6`은 입력 날짜로부터 6일에 대한 index 생성

In [216]:
df = pd.DataFrame(np.random.randint(0, 100, size = (6, 4)))

df.columns = ['A', 'B', 'C', 'D']
df.index = pd.date_range('20200701', periods = 6)
df.index

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
               '2020-07-05', '2020-07-06'],
              dtype='datetime64[ns]', freq='D')

결측값, 이상치 (NaN) 조작

- `df.dropna(how = "any")` : NaN 표기된 행 제거
    - "any" : 행의 성분에 NaN이 하나라도 있으면 제거
    - "all" : 행의 성분이 모두 NaN이면 제거
- `df.fillna(value = 값)` : NaN 성분이 있는 곳에, 일괄적으로 value 대입
- `df.isnull()` : NaN 성분만 True. NaN 포함된 데이터에 대한 boolean 마스크 생성
- `df.isnull().sum()` : column별 결측값 개수
- `df.isnull().sum(1)` : 행(row) 단위로 결측값 개수
- `df.loc[df.isnull()['F'], :]` : 'F' column에서 결측값을 포함하는 행 추출

In [217]:
df['F'] = [1.0, np.nan, 3.5, 6.1, np.nan, 7.0]

In [218]:
df.dropna(how = 'any')
df.dropna(how = 'all')

A   B   C   D    F
2020-07-01   6  63  74  60  1.0
2020-07-02  68  26  61  93  NaN
2020-07-03  50  73  92  79  3.5
2020-07-04  56  20  37  95  6.1
2020-07-05  38  76  41  46  NaN
2020-07-06  75   8  43  44  7.0

In [220]:
df.fillna(value = .5)

A   B   C   D    F
2020-07-01   6  63  74  60  1.0
2020-07-02  68  26  61  93  0.5
2020-07-03  50  73  92  79  3.5
2020-07-04  56  20  37  95  6.1
2020-07-05  38  76  41  46  0.5
2020-07-06  75   8  43  44  7.0

In [229]:
df.isnull()
df.isnull().sum()
df.isnull().sum(1)

2020-07-01    0
2020-07-02    1
2020-07-03    0
2020-07-04    0
2020-07-05    1
2020-07-06    0
Freq: D, dtype: int64

In [231]:
df.loc[df.isnull()['F'], :]
df.isnull()['F']

2020-07-01    False
2020-07-02     True
2020-07-03    False
2020-07-04    False
2020-07-05     True
2020-07-06    False
Freq: D, Name: F, dtype: bool

행/열 삭제

- `pd.to_datetime("날짜")` : 날짜명을 datetime 데이터형으로 변환
    - `pd.date_range()` : index에 접근하려면, datetime 데이터형을 인자로 삽입
- `pd.drop(index)` : index 행 삭제
- `del df["column명"]` : column 삭제

In [232]:
pd.to_datetime('20200701')

Timestamp('2020-07-01 00:00:00')

In [233]:
## 특정 행 drop
df.drop(pd.to_datetime('20200701'))
df.drop([pd.to_datetime('20200702'), pd.to_datetime('20200704')])

A   B   C   D    F
2020-07-01   6  63  74  60  1.0
2020-07-03  50  73  92  79  3.5
2020-07-05  38  76  41  46  NaN
2020-07-06  75   8  43  44  7.0

In [234]:
## 특정 열 삭제
df.drop('F', axis = 1)
df.drop(['B', 'D'], axis = 1)

A   C    F
2020-07-01   6  74  1.0
2020-07-02  68  61  NaN
2020-07-03  50  92  3.5
2020-07-04  56  37  6.1
2020-07-05  38  41  NaN
2020-07-06  75  43  7.0

Pandas 함수

In [235]:
data = [[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]]
df = pd.DataFrame(data, columns = ['one', 'two'], index = ['a', 'b', 'c', 'd'])

In [236]:
## 각 열의 합 (행방향 합)
df.sum(axis = 0)

## 각 행의 합 (열방향 합)
df.sum(axis = 1)

df.sum(axis = 1, skipna = False)

## 특정 행/열에서 계산
df['one'].sum()
df.loc['b'].sum()
df['one'].mean()

3.0833333333333335

NaN 값에 특정값 삽입

In [237]:
one_mean = df['one'].mean()
two_min = df['two'].min()

df['one'] = df['one'].fillna(value = one_mean)
df['two'] = df['two'].fillna(value = two_min)

정렬함수

- 기존 index, column 순서 섞기 위하여 `reindex()` 사용
    - index가 datetime 형식이라면, 변수에서 따로 빼내어 `np.random.permutation` 함수를 사용하여 섞고, columns는 자체적으로 섞어서 대입
- `.sort_index(axis = 0)` : index(행) 기준 오름차순 정렬
- `.sort_index(axis = 1)` : column(열) 기준 오름차순 정렬
- `.sort_index(axis = 0, ascending = False)` : index(행) 기준 내림차순 정렬
- `.sort_index(axis = 1, ascending = False)` : columns(열) 기준 내림차순 정렬

In [238]:
df2 = pd.DataFrame(np.random.randint(0, 100, size = (6, 4)),
                columns = ['A', 'B', 'C', 'D'],
                index = pd.date_range('20200701', periods = 6))

In [242]:
dates = df2.index
random_dates = np.random.permutation(dates)

df2 = df2.reindex(index = random_dates, columns = ['D', 'B', 'C', 'A'])
df2

D   B   C   A
2020-07-04  49  57  20  74
2020-07-03  47  26  56  12
2020-07-01  38  41  39  56
2020-07-06  98  75   1  16
2020-07-05  37  74  77  46
2020-07-02  89  90  10  12

In [243]:
df2.sort_index(axis = 0)
df2.sort_index(axis = 1) # column을 기준으로 정렬
df2.sort_index(axis = 1, ascending = False) # 내림차순 정렬

D   C   B   A
2020-07-04  49  20  57  74
2020-07-03  47  56  26  12
2020-07-01  38  39  41  56
2020-07-06  98   1  75  16
2020-07-05  37  77  74  46
2020-07-02  89  10  90  12

특정 열에 대해 정렬
- `.sort_values(by = "column")` : 특정열에 대해 오름차순 정렬
- `.sort_values(by = ["column A", "column B"])` : column A 기준으로 오름차순 정렬 후, 같은 값 있다면 column B 기준으로 오름차순 정렬

In [244]:
df2.sort_values(by = 'D')
df2.sort_values(by = 'B', ascending = False)

D   B   C   A
2020-07-02  89  90  10  12
2020-07-06  98  75   1  16
2020-07-05  37  74  77  46
2020-07-04  49  57  20  74
2020-07-01  38  41  39  56
2020-07-03  47  26  56  12

In [246]:
df2["E"] = np.random.randint(0, 6, size = 6)
df2["F"] = ['alpha', 'beta', 'gamma', 'gamma', 'alpha', 'gamma']

df2.sort_values(by = ['E', 'F'])

D   B   C   A  E      F
2020-07-05  37  74  77  46  0  alpha
2020-07-03  47  26  56  12  2   beta
2020-07-01  38  41  39  56  2  gamma
2020-07-04  49  57  20  74  4  alpha
2020-07-06  98  75   1  16  4  gamma
2020-07-02  89  90  10  12  4  gamma

그 외 함수들

In [247]:
df2['F'].unique() # 중복값 제외
df2['F'].value_counts() # 값의 개수
df2['F'].isin(['alpha', 'beta']) # 값 여부 확인

df2.loc[df2['F'].isin(['alpha', 'beta']), :]

D   B   C   A  E      F
2020-07-04  49  57  20  74  4  alpha
2020-07-03  47  26  56  12  2   beta
2020-07-05  37  74  77  46  0  alpha

##### 데이터 불러오기 및 저장하기

In [248]:
csv_test = pd.read_csv('test_csv_file.csv')
csv_test

ID LAST_NAME  AGE
0   1       KIM   30
1   2      CHOI   25
2   3       LEE   41
3   4      PARK   19
4   5       LIM   36

In [249]:
type(csv_test)
csv_test.shape

(5, 3)

In [251]:
text_test = pd.read_csv('test_text_file.txt', sep = '|')
text_test

ID  A  B  C  D
0  C1  1  2  3  4
1  C2  5  6  7  8
2  C3  1  3  5  7

In [255]:
## 파일 로드할 때, index 지정
text_test = pd.read_csv('test_text_file.txt', sep = '|', index_col = 0)
text_test

A  B  C  D
ID            
C1  1  2  3  4
C2  5  6  7  8
C3  1  3  5  7

In [256]:
text_test = pd.read_csv('test_text_file.txt', sep = '|', index_col = 'ID') # 변수 이름으로 지정
text_test

A  B  C  D
ID            
C1  1  2  3  4
C2  5  6  7  8
C3  1  3  5  7

In [258]:
## 변수 이름이 없는 경우, 이름 부여
# header = None : column 이름이 없다. 1번째 행이 column name이면 header = 0
text_test = pd.read_csv('text_without_column_name.txt', sep = '|', names = ['ID', 'A', 'B', 'C', 'D'], header = None, index_col = 'ID')
text_test

A  B  C  D
ID            
C1  1  2  3  4
C2  5  6  7  8
C3  1  3  5  7

In [259]:
## 특정 행 제외하고 로드
csv_test = pd.read_csv('test_csv_file.csv', skiprows = [1, 2])
csv_test

ID LAST_NAME  AGE
0   3       LEE   41
1   4      PARK   19
2   5       LIM   36

In [260]:
## n개의 행만 로드
csv_test = pd.read_csv('test_csv_file.csv', nrows = 3)
csv_test

ID LAST_NAME  AGE
0   1       KIM   30
1   2      CHOI   25
2   3       LEE   41

엑셀 파일 불러오기 `pd.read_excel()`
- `sheet_name` 기입하지 않으면 첫번째 시트 로드

데이터 저장하기

In [261]:
## csv 파일로 내보내기
data = {'ID' : ['A1', 'A2', 'A3', 'A4', 'A5'],
        'X1' : [1, 2, 3, 4, 5],
        'X2' : [3.0, 4.5, 3.2, 4.0, 3.5]}

data_df = pd.DataFrame(data, index = ['a', 'b', 'c', 'd', 'e'])
data_df

ID  X1   X2
a  A1   1  3.0
b  A2   2  4.5
c  A3   3  3.2
d  A4   4  4.0
e  A5   5  3.5

In [262]:
## 새로운 행, 결측값 추가
data_df_2 = data_df.reindex(['a', 'b', 'c', 'd', 'e', 'f'])
data_df_2

ID   X1   X2
a   A1  1.0  3.0
b   A2  2.0  4.5
c   A3  3.0  3.2
d   A4  4.0  4.0
e   A5  5.0  3.5
f  NaN  NaN  NaN

In [264]:
data_df_2.to_csv('data_df_2.csv', sep = ',', na_rep = 'NaN') # 결측값 포기